services:
  postgres_db:
    image: postgres:16.1
    container_name: exp-postgres-cnt
    environment:
      POSTGRES_PASSWORD: mypass
      POSTGRES_USER: msm-faraj
      POSTGRES_DB: exp_db
    ports:
      - 5000:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data

  server:
    build: ./exp-server
    container_name: exp-server-cnt
    ports:
      - 4000:4000
    networks:
      - expense_tracker
    volumes:
      - ./exp-server:/exp-server

  client:
    build: ./exp-client
    container_name: exp-client-cnt
    ports:
      - 3000:3000
    networks:
      - expense_tracker
    volumes:
      - ./exp-client:/exp-client

networks:
  expense_tracker:
    driver: "bridge"

volumes:
  postgres_db:
    driver: local
