#this is a dockerfile for react app

FROM node:21-alpine3.18 

WORKDIR /exp-client

COPY package*.json ./

RUN npm install

COPY  src ./src

#COPY  public ./public

COPY . ./

CMD ["npm", "run", "start"]
